### ISSUE TITLE
[NEW]: Permanently on show at "The Sumida Hokusai Museum"

### ISSUE THREAD

**Issue by kevinarpe** [gingerbeardman/greatwavetoday#1]
### Organisation name

The Sumida Hokusai Museum

### Online collection?

- [ ] collection is online

### On view status visible?

- [ ] on view status is visible

### Original impression?

- [X] we have an original impression

**Comment by gingerbeardman** [comment]
Hi @kevinarpe do you work at or for the Sumida museum?

I reached out to Sumida some time ago but didn't hear back.

**Comment by kevinarpe** [comment]
I do not work at the museum.  As a resident of Tokyo, I have visited
the museum multiple times.  An original print of big wave is always on show
in the permanent exhibition.

**Comment by gingerbeardman** [comment]
I just found this reference:

https://spice.eplus.jp/articles/241938

> 葛飾北斎 「冨嶽三十六景 神奈川沖浪裏」 (通期) 作品を替えて通期で展示 すみだ北斎美術館蔵

> Katsushika Hokusai "Thirty-six Views of Mt.Fuji, The Great Wave off Kanagawa" (full year) Alternating works on display throughout the year Sumida Hokusai Museum Collection

**Comment by gingerbeardman** [comment]
This has been added in the latest update!

Thank you
